site_name: ""
theme:
  name: material
  logo: assets/logo.png

  custom_dir: docs/overrides

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - announce.dismiss
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  generator: false

  tags:
    pending: pending
    passed: passed
    failed: failed

  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our website and whether users
      find what they're searching for. With your consent, you're helping us to
      make our website better.

repo_name: tkufi/Turku-Legislation
repo_url: https://github.com/tkufi/Turku-Legislation
site_url: https://tkufi.github.io/Turku-Legislation/

markdown_extensions:
  - toc:
      permalink: ¶

plugins:
  - search
  - tags
